title: 測試模式 Test Mode
teams:
    Team A:
        source: "Wonder4.py"
        color: "#1d4ed8"
    Team B:
        source: ""
        color: "#e11d48"
delay:
    step: 200
    set: 2000
competition:
    rule: double-sided
    matches:
        -
            type: empty
        -
            type: random
            count: 4
        -
            type: random
            count: 8
            ext: true
    timeout:
        step: 999999999
        set: 999999999
